name: Deploy Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_MAIL: ${{ secrets.HEROKU_MAIL }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Initi Variables
        run: echo "MY_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: $HEROKU_API_KEY
          heroku_app_name: rg-be-${{env.MY_DATE}}
          heroku_email: $HEROKU_MAIL
          usedocker: true
