name: Deploy Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_MAIL: ${{ secrets.HEROKU_MAIL }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: $HEROKU_API_KEY
          heroku_app_name: robot-game.backend:$(date +%s)
          heroku_email: $HEROKU_MAIL
          usedocker: true
